# Generated by Django 4.2 on 2023-04-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoothie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smoothieingredient',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
