# Generated by Django 4.2 on 2023-04-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoothie', '0002_smoothieingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='smoothie',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0 stars'), (1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=0, null=True),
        ),
    ]
